services:
  vue_app:
    platform: linux/amd64 # Mueve platform al nivel del servicio
    build:
      context: . # Especifica el contexto de construcción
      dockerfile: Dockerfile # Define el archivo Dockerfile que se usará
    ports:
      - "8080:80" # Mantén tus puertos
    volumes:
      - .:/app # Mantén los volúmenes si son necesarios
    environment:
      - NODE_ENV=development # Mantén las variables de entorno
    container_name: vue_app_container # Mantén el nombre del contenedor si lo necesitas